#! /bin/bash

# From https://htcondor-wiki.cs.wisc.edu/index.cgi/wiki?p=CondorInTheCloudSeedConstruction

# This script does EC2 cleanup after instance installation:
# The following, if copied and pasted into a terminal window just before
# you hit 'create image', makes the image more suitable for general
# usage: it turns off bash history, clears the bash history, and removes
# the bash history file; it also removes (all?) HTCondor history files,
# so the AMI's HTCondor starts up with a clean state; and then cleans up
# the root and current user's SSH keys and known hosts, and also root's
# bash history.

set +o history
history -c
rm -fr ~/.bash_history
sudo rm -fr /var/log/condor/*
sudo rm -fr /var/run/condor/*
sudo rm -fr /var/lock/condor/InstanceLock
sudo rm -fr /var/lib/condor/execute/*
sudo rm -fr /var/lib/condor/spool/*
sudo rm -fr /etc/condor/config.d/49ec2-instance.config
sudo rm -fr /etc/condor/config.d/password_file.pl
sudo /bin/sh -c 'rm -fr ~/.bash_history'
sudo /bin/sh -c 'rm -fr ~/.ssh/authorized_keys'
sudo /bin/sh -c 'rm -fr ~/.ssh/known_hosts'
rm -fr ~/.ssh/authorized_keys
rm -fr ~/.ssh/known_hosts
git checkout -- supporting_files

