#! /bin/bash

USER=ec2-user

# ..................................................................................
echo "============================================================"
echo "This script installs HTCondor and condor_annex on a yum-based EC2 instance."
echo "============================================================"

echo "Installing EPEL repo"
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# ..................................................................................
# From https://research.cs.wisc.edu/htcondor/instructions/el/7/development/
echo "============================================================"
echo "Setting up HTCondor cs.wisc repo and starting condor service"
wget https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
sudo rpm --import RPM-GPG-KEY-HTCondor
(cd /etc/yum.repos.d; sudo wget https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-prerelease-amzn2.repo)

sudo yum install -y condor-all

sudo systemctl enable condor
sudo systemctl start condor

ps ax | grep condor

# ..................................................................................
# From https://htcondor-wiki.cs.wisc.edu/index.cgi/wiki?p=CondorInTheCloudSeedConstruction
sudo yum install -y condor-annex-ec2
sudo yum install -y python-pip

sudo pip install --upgrade pip
sudo pip install awscli

# ..................................................................................
echo "Add an AWS role which can run condor_annex and assign it to this EC2."

echo "Installing local as /etc/condor/config.d/local"
sudo cp  -v supporting_files/local   /etc/condor/config.d/local

# ..................................................................................
echo "Enabling condor-annex-ec2 service"
sudo systemctl enable condor-annex-ec2

echo "Removing /etc/condor/config.d/xxxxx.config"
sudo rm -v /etc/condor/config.d/50ec2.config

echo "Copying condor-annex-ec2 to /usr/libexec/condor/condor-annex-ec2"
sudo cp -v supporting_files/condor-annex-ec2  /usr/libexec/condor/condor-annex-ec2

echo "Starting service condor-annex-ec2"
sudo systemctl start  condor-annex-ec2

echo "Make up a Condor SEC_PASSWORD_FILE password"
passwd_file=`sudo condor_config_val SEC_PASSWORD_FILE`
sudo condor_store_cred -c add -f $passwd_file
sudo chown root.root $passwd_file
sudo chmod 600 $passwd_file

echo "Installing /home/$USER/.condor"
mkdir -p /home/$USER/.condor
sudo cp supporting_files/dot_condor/*  /home/$USER/.condor
sudo cp $passwd_file /home/$USER/.condor
sudo chown -R $USER.$USER /home/$USER/.condor
chmod 600 /home/$USER/.condor/*

condor_restart
