#! /bin/bash -x

function cont () {
   echo -n "Continue (y/n)?"
   while true; do
       read -p "Continue (y/n)?" yn
       case $yn in
           [Yy]* ) make install; break;;
           [Nn]* ) exit;;
           * ) echo "Please answer yes or no.";;
       esac
   done
}

# ..................................................................................
echo "============================================================"
echo "This script installs HTCondor and condor_annex on an AWS EC2 RHEL-7.6 instance."
echo "Updating Linux with yum."
yum update yum
yum update
yum install wget
cont()

# ..................................................................................
# From https://research.cs.wisc.edu/htcondor/instructions/el/7/development/
echo "============================================================"
echo "Setting up HTCondor cs.wisc repo and starting condor service"
wget https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
rpm --import RPM-GPG-KEY-HTCondor
cd /etc/yum.repos.d
wget https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-development-rhel7.repo

yum install condor-all

systemctl start condor
systemctl enable condor

ps ax | grep condor
cont()

# ..................................................................................
# From https://htcondor-wiki.cs.wisc.edu/index.cgi/wiki?p=CondorInTheCloudSeedConstruction
yum install condor-annex-ec2

yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install python-pip
pip install --upgrade pip
pip install awscli

# ..................................................................................
echo "Add an AWS role which can run condor_annex and assign it to this EC2."
cont()

echo "Installing local as /etc/condor/config.d/local"
cp  -v supporting_files/local   /etc/condor/config.d/local

# ..................................................................................
echo "Enabling condor-annex-ec2 service"
systemctl enable condor-annex-ec2

echo "Removing /etc/condor/config.d/xxxxx.config"
rm -v /etc/condor/config.d/50ec2.config

echo "Copying condor-annex-ec2 to /usr/libexec/condor/condor-annex-ec2"
cp -v supporting_files/condor-annex-ec2  /usr/libexec/condor/condor-annex-ec2

echo "Starting service condor-annex-ec2"
systemctl enable condor-annex-ec2

echo "Enter Condor SEC_PASSWORD_FILE password"
passwd_file=`condor_config_val SEC_PASSWORD_FILE`
condor_store_cred -c add -f $passd_file
chown root.root $passwd_file
chmod 600 $passwd_file

echo "Creating ~ec2-user/.condor"
mkdir ~ec2-user/.condor

echo "Installing ~ec2-user/user_config"
cp supporting_files  ~ec2-user/.condor/user_config
