#! /bin/sh

sudo docker network create -d bridge elknet

for comp in `cat components`;
do
    echo ============== building $comp =================
    cd $comp
    ./build
    cd ..
done

echo ================= docker image ls =================
docker image ls
