#! /bin/bash

if [[ `docker network ls | awk '{ print $2 }' | grep elknet` == "" ]]; then
    docker network create -d bridge elknet
fi

components=${1:-`cat components`}

for comp in $components;
do
    echo ============== building $comp =================
    cd $comp
    ./build
    cd ..
done

echo ================= docker image ls =================
docker image ls
