#! /bin/bash

components=${1:-`cat components`}

for comp in $components;
do
    echo =============== starting $comp =================
    $comp/run
done

echo =================== docker ps ======================
docker ps

