#!  /bin/sh

sudo chown root.root condorbeat.yml
sudo chmod 644 condorbeat.yml

sudo docker run -v `pwd`/condorbeat.yml:/condorbeat/condorbeat.yml --name condorbeat -d retzkek/condorbeat

sudo sysctl -w vm.max_map_count=262144
sudo sysctl -w fs.file-max=65536

sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --ulimit nofile=65536:65536 --name elk sebp/elk

# docker-compose is theoretically better than the docker run above,  but has dependency issues ATM.
# sudo docker-compose up elk

