#! /bin/sh

for comp in `cat components`;
do
    echo =================== stopping htc-$comp ====================
    docker container stop htc-$comp
    docker container rm htc-$comp
done

echo ==================== docker containers ======================
docker container ls -a

