#! /bin/sh

components=${1:-`cat components`}

for comp in $components;
do
    echo =================== stopping htc-$comp ====================
    docker container stop htc-$comp
    docker container rm htc-$comp
done

echo ==================== docker containers ======================
docker container ls -a

