FROM docker.elastic.co/beats/metricbeat:7.6.1

COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml

# USER root
# RUN metricbeat modules enable docker
# COPY docker.yml /usr/share/metricbeat/modules.d/docker.yml

USER root
RUN chown root:metricbeat /usr/share/metricbeat/metricbeat.yml  && \
    chmod 644 /usr/share/metricbeat/metricbeat.yml

# /usr/share/metricbeat/modules.d/docker.yml /usr/share/metricbeat/data/meta.json

USER metricbeat

