FROM docker.elastic.co/beats/metricbeat:6.6.2

COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml

USER root
RUN metricbeat modules enable docker
COPY docker.yml /usr/share/metricbeat/modules.d/docker.yml

USER root
RUN chown -R root:metricbeat /usr/share/metricbeat && \
    chmod 640 /usr/share/metricbeat/metricbeat.yml && \
    chmod 640 /usr/share/metricbeat/data/meta.json

# /usr/share/metricbeat/modules.d/docker.yml /usr/share/metricbeat/data/meta.json

USER metricbeat

