FROM docker.elastic.co/beats/metricbeat:6.6.2

USER root
COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml
COPY docker.yml /usr/share/metricbeat/modules.d/docker.yml

RUN metricbeat modules enable docker

RUN chown -R root:metricbeat /usr/share/metricbeat && \
    chmod 640 /usr/share/metricbeat/metricbeat.yml && \
    chmod 640 /usr/share/metricbeat/data/meta.json

# /usr/share/metricbeat/modules.d/docker.yml /usr/share/metricbeat/data/meta.json

# USER metricbeat

