metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false
- module: docker
  metricsets:
    - container
    - cpu 
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

output.elasticsearch:
  hosts: ["htc-elasticsearch"]
  index: "metricbeat-%{+yyyy.MM.dd}"

setup:
  template:
      name: "metricbeat"
      pattern: "metricbeat-*"
  kibana:
      host: "htc-kibana"

system:
   hostfs: "/hostfs"
