#! /bin/bash

docker run -d \
  --name htc-metricbeat \
  --net=host \
  --mount type=bind,source=/proc,target=/hostfs/proc,readonly \
  --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly \
  --mount type=bind,source=/,target=/hostfs,readonly \
  -e -system.hostfs=/hostfs \
  htc-metricbeat 

# docker exec htc-metricbeat   metricbeat setup && metricbeat -e
