#! /bin/bash

docker run -it \
  --name htc-metricbeat \
  --net=host \
  --mount type=bind,source=/proc,target=/hostfs/proc,readonly \
  --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly  \
  --mount type=bind,source=/,target=/hostfs,readonly \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,readonly \
  htc-metricbeat \
  metricbeat -e -system.hostfs=/hostfs

docker exec  htc-metricbeat   metricbeat setup


