#! /bin/bash

docker run --rm htc-metricbeat setup

docker run -d \
  --name htc-metricbeat \
  --network elknet \
  --mount type=bind,source=/proc,target=/hostfs/proc,readonly \
  --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly  \
  --mount type=bind,source=/,target=/hostfs,readonly \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,readonly \
  htc-metricbeat  metricbeat -e  -system.hostfs=/hostfs


